### ISSUE TITLE
Gem Dependency Roadmap

### ISSUE THREAD

**Issue by nvick** [concord-consortium/rigse#454]
_From @nvick on April 9, 2018 23:7_

This roadmap was created by simulating each upgrade step with bundler. At each step we update rails to the next non-patch release, then work through the dependency resolution process until the Gemfile successfully bundles. 

## Pre Rails 4.0 upgrade

These gems will need to be ugpraded to the listed versions by Rails 4.0, but can be done in advance of the Rails upgrade.

- [ ] devise 2.1.3 -> 3.1.2
- [ ] acts-as-taggable-on 2.1.1 -> 2.4.1 _gem was not caught bundler. This is a gem we have had experience with during upgrades._
- [ ] cc_portal_wordpress_integration
- [ ] cc_portal_remote_auth
- [ ] geniverse_portal_integration
- [ ] genigames_connector
- [ ] calpicker

## Upgrade at Rails 4.0

- [ ] sass-rails 3.2.6 -> 5.0.7 _had to push this all the way up to get a compatible version of sass for compass-rails_
- [ ] compass-rails 2.0.4 -> 3.0.2
- [ ] coffee-rails 3.2.2 -> 4.0.1
- [ ] activerecord-import 0.2.9 -> 0.4.1

## Add at Rails 4.0 

- [ ] protected_attributes
- [ ] activerecord-session_store
- [ ] rails-observers

## Remove at Rails 4.0

- [ ] strong_parameters
- [ ] turbo-sprockets-rails3

## Upgrade by Rails 4.1
- No gems to be upgraded at this step (based on gemspec)

## Upgrade by Rails 4.2
- No gems to be upgraded at this step (based on gemspec)

_Copied from original issue: hintmedia/rigse#2_

**Comment by nvick** [comment]
Based on our experience and the age of the dependencies in the Gemfile we believe there will be number of dependencies that will require updating during each step that bundler was not able to catch due to loose assertions in gemspec files. An example of that is the acts-as-taggable-on gem which we know needs to be updated at Rails 4.0, but can be updated at Rails 3.2.

**Comment by emilywatkins** [comment]
@scytacki It looks like calpicker_includes is still used in layouts such that removing calpicker from the gemfile broke a good chunk of the rspec and cucumber test suites.

It's used in the following files:
spec/views/layouts/application.html.haml_spec.rb
app/views/layouts/application.html.haml
app/views/layouts/minimal.html.haml
app/views/layouts/report.html.haml
app/views/layouts/run.run_html.haml

Please advise on how you'd like to proceed.
